image: docker:git
services:
  - docker:dind

before_script:
  - docker info

build_image:
  script:
    - docker build -t registry.gitlab.com/kathra/kathra/kathra-services/kathra-pipelinemanager/kathra-pipelinemanager-java/kathra-pipelinemanager-jenkins:latest .
    - docker push registry.gitlab.com/kathra/kathra/kathra-services/kathra-pipelinemanager/kathra-pipelinemanager-java/kathra-pipelinemanager-jenkins:latest